#!/bin/bash
if [ ! -f /etc/firstboot ]; then
	rpcu=$(pwgen -ncsB 35 1)
	rpcp=$(pwgen -ncsB 75 1)
	
	echo "rpcuser=$rpcu
rpcpassword=$rpcp" >> /home/pi/.whitecoin-xwc/whitecoin.conf
	
	sudo tzupdate
	sudo openssl req -x509 -nodes -days 3650 -subj "/C=US/ST=Whitecoin/L=Whitecoin/O=Whitecoin/CN=whitenode.local" -newkey rsa:2048 -out /etc/nginx/ssl/whitenode.crt -keyout /etc/nginx/ssl/whitenode.key

        sudo update-rc.d ssh disable
        sudo invoke-rc.d ssh stop
        sudo echo "sshserver=off" >> /boot/config.txt
	
        sudo touch /etc/firstboot
fi

if [ -f /boot/wallet/wallet.dat ]; then
		if [ -f /home/pi/.whitecoin-xwc/wallet.dat ]; then
			DATE=`date '+%Y%m%d%H%M%S'`
		
			sudo mv /home/pi/.whitecoin-xwc/wallet.dat /home/pi/.whitecoin-xwc/wallet_${DATE}.dat
		fi
		
		sudo mv /boot/wallet/wallet.dat /home/pi/.whitecoin-xwc/wallet.dat
		sudo chown pi.pi /home/pi/.whitecoin-xwc/wallet.dat
fi

if [ -f /var/www/public/.reboot ]; then
    rm -f /var/www/public/.reboot
fi
