#!/usr/bin/env bash
# Whitecoin Node
# Written by Oizopower
# GPL V3
########

set -x
set -e

# Source error handling, leave this in place
source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/boot /boot
unpack /filesystem/root /

apt-get update

#install needed files
apt-get install -y ntp unzip git build-essential libdb-dev libdb++-dev libboost-all-dev libqrencode-dev miniupnpc libminiupnpc-dev zlib1g-dev pwgen

#create Whitecoin config file
rpcu=$(pwgen -ncsB 35 1)
rpcp=$(pwgen -ncsB 75 1)

echo "rpcuser=$rpcu
rpcpassword=$rpcp" >> /home/pi/.whitecoin-xwc/whitecoin.conf

# compile openssl from source
cd /usr/src
wget https://www.openssl.org/source/openssl-1.0.2k.tar.gz
tar zxvf openssl-1.0.2k.tar.gz
cd openssl-1.0.2k
export CFLAGS="-fPIC"
./config --prefix=/usr --openssldir=/usr/local/openssl shared enable-ec enable-ecdh enable-ecdsa
make all
make install

# clone whitecoin and compile
git clone https://github.com/Whitecoin-org/whitecoin /opt/whitecoin
cd /opt/whitecoin/src/ && make -f makefile.unix OPENSSL_INCLUDE_PATH=/usr/src/openssl-1.0.2k/include OPENSSL_LIB_PATH=/usr/src/openssl-1.0.2k/lib

#strip whitecoind
strip whitecoind

# copy whitecoind to other place
cp -R -r -p whitecoind /usr/local/bin/

# cleanup
rm -rf /opt/whitecoin

#override timezone
if [ "$WHITECOIN_OVERRIDE_TIMEZONE" != "default" ]
then
    echo "$WHITECOIN_OVERRIDE_TIMEZONE" > /etc/timezone
    dpkg-reconfigure -f noninteractive tzdata
fi

#override locale
if [ "$WHITECOIN_OVERRIDE_LOCALE" != "default" ]
then
    sed -i '/^#.* '"$WHITECOIN_OVERRIDE_LOCALE"' /s/^# //' /etc/locale.gen
    locale-gen
    update-locale LANG="$WHITECOIN_OVERRIDE_LOCALE"
fi

#override password
if [ "$WHITECOIN_OVERRIDE_PASSWORD" != "default" ]
then
    echo "pi:$WHITECOIN_OVERRIDE_PASSWORD" | chpasswd
fi

echo "exit 0" >> /etc/rc.local

echo "server time.nist.gov" >> /etc/ntp.conf
echo "server ntp.ubuntu.com" >> /etc/ntp.conf

#set systemd startup files
systemctl daemon-reload
systemctl start whitecoin
systemctl enable whitecoin

#cleanup
apt-get clean
apt-get autoremove -y
