#!/usr/bin/env bash
# Whitecoin Node
# Written by Oizopower
# GPL V3
########

set -x
set -e

# Source error handling, leave this in place
source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/boot /boot
unpack /filesystem/root_init /

apt-get update -y
apt-get upgrade -y

#set cron for backups
crontab -l -u pi | echo "0 0 * * * sh /home/pi/scripts/backupwallet >/dev/null 2>&1" | crontab -u pi -

#install needed files
apt-get install -y ntp unzip zip git build-essential libdb-dev libdb++-dev libboost-all-dev libqrencode-dev miniupnpc libminiupnpc-dev zlib1g-dev pwgen libssl1.0-dev python-pip php7.0 php7.0-curl php7.0-gd php7.0-fpm php7.0-cli php7.0-opcache php7.0-mbstring php7.0-xml php7.0-zip php7.0-intl nginx-light zip

# add latest blockchain files
cd /home/pi/.whitecoin-xwc
wget https://github.com/Whitecoin-org/xwc-blockchain/releases/download/latest/xwc-blockchain.zip
/usr/bin/unzip xwc-blockchain.zip
rm -f xwc-blockchain.zip
chown pi.pi *

# set correct timezone
pip install -U tzupdate

#set config permissions
sed -i 's,^\(user \).*,\1'pi\;',' /etc/nginx/nginx.conf
sed -i 's,^\(user = \).*,\1'pi',' /etc/php/7.0/fpm/pool.d/www.conf
sed -i 's,^\(group = \).*,\1'pi',' /etc/php/7.0/fpm/pool.d/www.conf

#update startup scripts
update-rc.d nginx defaults
update-rc.d php7.0-fpm defaults

# Generate RPC first Boot
chmod +x /home/pi/scripts/firstboot /home/pi/scripts/backupwallet
systemctl enable whitenode_first_boot.service

# Startup Whitecoin service
systemctl enable whitecoin.service

#nginx config file
cat > /etc/nginx/sites-enabled/default << "EOF"
# Default server configuration
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name _;
	return 301 https://$host$request_uri;
}

server {
        listen 443 ssl;
		
        ssl_certificate /etc/nginx/ssl/whitenode.crt;
        ssl_certificate_key /etc/nginx/ssl/whitenode.key;

        root /var/www/public;

        error_log /var/www/logs/error_log;
        access_log /var/log/nginx/access.log;

        index index.html index.htm index.php default.html;

        server_name _;

        location / {
		
				# allow local networks
                allow   192.168.0.0/16;
                allow   10.0.0.0/16;
                allow   172.16.0.0/16;
                # drop rest of the world
                deny    all;

                if (-f $request_filename) {
                    break;
                }
                rewrite ^/(.*)$ /index.php?rewriteurl=$1 last;
        }

        # pass the PHP scripts to FastCGI server
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        }
		
		location ~* \.(git|rb|inc|ht|ini)$ {
                deny all;
        }

         location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                expires max;
                log_not_found off;
        }

        # deny access to .htaccess files, should an Apache document root conflict with nginx
        location ~ /\.ht {
                deny all;
        }
}

EOF

#create nginx docroot folders
mkdir -p /var/www/{public,private,logs,backup,vhosts}

# prepare interface
cd /var/www/public
git clone https://github.com/Oizopower/WhiteNode-GUI.git .

#set permissions
sudo chown pi:pi -R /var/www
sudo usermod -a -G www-data pi

# Generate default SSL certificate
mkdir -p /etc/nginx/ssl/
openssl req -x509 -nodes -days 3650 -subj "/C=US/ST=Whitecoin/L=Whitecoin/O=Whitecoin/CN=whitenode.local" -newkey rsa:2048 -out /etc/nginx/ssl/whitenode.crt -keyout /etc/nginx/ssl/whitenode.key

# clone whitecoin and compile
git clone https://github.com/Whitecoin-org/whitecoin /opt/whitecoin
cd /opt/whitecoin/src/ && make -f makefile.unix USE_UPNP=1

# copy whitecoind to other place
cp -R -r -p whitecoind /usr/local/bin/
cd /usr/local/bin/

# strip whitecoind
strip whitecoind

echo "exit 0" >> /etc/rc.local

#unpack /filesystem/root /

# cleanup
rm -rf /opt/whitecoin
rm -rf /home/oizopower

# cleanup
apt-get clean
apt-get autoremove -y

echo "ALL DONE !!!!";
